### PR TITLE
Add Sparrow

### PR DESCRIPTION
**Pull request by melezhik**

### CODE REVIEW

**Comment by melezhik** [comment]
Hi @k4m4 , do you need any help with PR ?

**Comment by k4m4** [comment]
Hello @melezhik. Could you resolve the conflicts with master? Thanks.

**Comment by melezhik** [comment]
Hopefully I did this ... 😄

**Comment by melezhik** [comment]
Hi @k4m4 , any news here ?

**Comment by k4m4** [comment]
Hi again @melezhik. I just noticed that I never replied to your final message. Please have a look at the `contributing.md` file for more information on the `endorsement-needed` tag. Thanks again and apologies for the very late response.

**Comment by melezhik** [comment]
@k4m4  this PR is no longer needed.

**Pull request closed without merging**
