### PR TITLE
Add GNOME Terminal

### PR DESCRIPTION
**Pull request by f2404**
## Checklist for submitting a pull request to `Terminals Are Sexy`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/terminals-are-sexy/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/terminals-are-sexy/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: GNOME Terminal
- **Link**: https://wiki.gnome.org/Apps/Terminal
- **Category**: Terminal emulator
- **Description**: A terminal emulator for GNOME.

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
I can endorse GNOME Terminal! 👍

**Comment by k4m4** [comment]
Hey there @f2404. Please resolve conflicts with master. Thanks!

**Comment by f2404** [comment]
Done!

**Comment by k4m4** [comment]
Thanks! Please also squash your commits into one.

**Comment by f2404** [comment]
Done.

**Pull request merged**
