### PR TITLE
Add hub to tools and plugins

### PR DESCRIPTION
**Pull request by mesaugat**
[hub](https://hub.github.com/) is a command-line wrapper for git that makes you better at GitHub.

hub makes it easier to fetch repositories, navigate project pages, fork repos and even submit pull requests, all from the command-line.

### CODE REVIEW

**Comment by mesaugat** [comment]
Sorry for the trouble. There was a conflict due to indentation. I don't know why. I hope the merge commit is not an issue.

**Comment by mesaugat** [comment]
I was behind master by some commits. Stupid me. It should be good now.

**Comment by k4m4** [comment]
No problem buddy.
There still seems to be a conflict, though.

**Comment by mesaugat** [comment]
Rebased.

**Pull request merged**
