### PR TITLE
Add oh-my-bash

### PR DESCRIPTION
**Pull request by glats**
## Checklist for submitting a pull request to `Terminals Are Sexy`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/terminals-are-sexy/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/terminals-are-sexy/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: Oh my bash
- **Link**: [https://github.com/ohmybash/oh-my-bash](https://github.com/ohmybash/oh-my-bash)
- **Category**: Bash
- **Description**: A delightful community-driven framework for managing your bash configuration.

### CODE REVIEW

**Comment by k4m4** [comment]
Thank you for your contribution @glats. Please drop the leading `A` and squash your commits. Thanks in advance.

**Comment by glats** [comment]
@k4m4 done!

**Comment by k4m4** [comment]
Hi @glats. There's still two commits at the moment. Please also make sure that you keep a descriptive commit name. Thanks!

**Comment by glats** [comment]
Ok. I think we are ready. Was my first time squashing commits so was tricky for me

**Comment by k4m4** [comment]
No worries, @glats. We are all here to learn new things! I would greatly appreciate it if you could change the commit name to `Add oh-my-bash`. Thanks again.

**Comment by glats** [comment]
done!

**Pull request closed without merging**
