### PR TITLE
Replace Powerlevel9k with Powerlevel10k

### PR DESCRIPTION
**Pull request by romkatv**
Powerlevel10k is an improved drop-in replacement for Powerlevel9k.

- Backward compatible. Produces the same prompt as Powerlevel9k given the same configuration.
- Between 10 and 100 times faster.
- Lots of extra features: responsive directory shortening, interactive configuration wizard, etc.

## Checklist for submitting a pull request to `Terminals Are Sexy`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/terminals-are-sexy/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/terminals-are-sexy/pulls) of this repo and believe that this is not a duplicate.

- **Title**: Powerlevel10k
- **Link**: https://github.com/romkatv/powerlevel10k/
- **Category**: ZSH
- **Description**: Fast and improved reimplementation of Powerlevel9k

### CODE REVIEW

**Comment by k4m4** [comment]
Hi there @romkatv. Could you please squash your commits? Thanks!

**Comment by romkatv** [comment]
> Hi there @romkatv. Could you please squash your commits? Thanks!

Done.

**Comment by romkatv** [comment]
Is there anything I need to do to get this PR merged?

**Comment by k4m4** [comment]
Hey @romkatv. Powerlevel9k doesn't seem to be deprecated so I would suggest creating a new pull request that adds Powerlevel10k instead of replacing Powerlevel9k. Also, have a look at the [contribution docs](https://github.com/k4m4/terminals-are-sexy/blob/master/contributing.md) for more info on the `endorsement-needed` label. Thanks!

**Comment by romkatv** [comment]
Thanks for the response, @k4m4! I'll close the PR.

**Pull request closed without merging**
