### PR TITLE
Alphabetically sorted lists

### PR DESCRIPTION
**Pull request by nojvek**
## Checklist for submitting a pull request to `Terminals Are Sexy`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/terminals-are-sexy/blob/master/contributing.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/k4m4/terminals-are-sexy/pulls) of this repo and believe that this is not a duplicate.

### CODE REVIEW

**Comment by k4m4** [comment]
Hi there! Thanks for sorting the list. Please separate your addition and the sorting into two different PRs. Thanks!

**Comment by nojvek** [comment]
@k4m4 , it's just the sorting now.

**Comment by k4m4** [comment]
Great, just squash the two commits into one and we're all set.

**Comment by nojvek** [comment]
Done

**Comment by k4m4** [comment]
Thanks!

**Comment by k4m4** [comment]
Fixes #194.

**Pull request merged**
