### PR TITLE
Added more stuffs

### PR DESCRIPTION
**Pull request by SentinelWarren**
Added More Package Managers

### CODE REVIEW

**Comment by k4m4** [comment]
Hi Alex. I've updated the repo. Please create a new pull req which will merge with the updated markdown. Thanks.

**Comment by SentinelWarren** [comment]
@k4m4 Ok,i am on it,

**Comment by SentinelWarren** [comment]
@k4m4 and i will create another pull with everything sorted in alphabet order,what do you think?

**Comment by k4m4** [comment]
Hi there. Please use one pull request per suggestion. Thanks!

**Pull request closed without merging**
